### ISSUE TITLE
doc: glsl-parameter does not work for compiled programs

### ISSUE THREAD

**Issue by kristianlm** [AlexCharlton/glls#5]
I don't know how you'd like us to contribute, but I though I'd mention that I was a little confused by the glsl-version parameter. It wasn't taking effect when I added it in in the examples. Now I realise it was because I was compiling them, and the parameter is (not so obviously) changed at runtime.

Can we add something like "note that the glsl-parameter has no effect for compiled programs" on the wiki?

And also, I tried `(begin-for-syntax (glsl-version 130))` but that didn't work. Any idea how to do this?

**Comment by AlexCharlton** [comment]
I'm pretty open to contributions in whatever form you want to make them. I see you've forked this repo, so pull requests are perfect!

As for this issue, you were very close! `begin-for-syntax` was the right move, but it won't work on its own since the parameter won't exist at syntax time unless you `(use-for-syntax glls)` first. I'll add a note in the docs!

**Comment by kristianlm** [comment]
Oh, that's why that wasn't working! So far the shader code has been identical for all my GLSL version, so I've had bigger problems getting the version declaration right than the actual code differences. Thanks!

**Comment by AlexCharlton** [comment]
It's too bad that versions have been such a headache for you, but thanks for trucking through it! Hypergiant et al definitely needs some usability improvements, which I hope to start working on in the new year. First I need to finish the audio library I'm working on, though ;)

**Comment by kristianlm** [comment]
It's still very impressive, I think! Usability is always hard.
